name: SurvivalUtils
version: ${version}
author: Crafty
main: de.crafty.survivalutils.SurvivalUtils


api-version: 1.19


commands:
  ping:
    usage: /ping
    description: Just your ping
    permission-message: You do not have the permission to use this command (Noob?)

  playtime:
    usage: /playtime
    description: Look at someones playtime
    permission-message: You do not have the permission to use this command (Noob?)

  invsee:
    usage: /invsee <Player>
    description: Invsee

  enderchest:
    usage: /enderchest
    description: Open your enderchest
    aliases: ec

  permission:
    usage: /permission <add|remove> <player> <permission>
    description: Give or remove a permission
    permission: survivalutils.cmd.permission
    permission-message: You do not have the permission to use this command (Noob?)


  coords:
    usage: /coords <create|retrieve|remove> <public|private> <name> (x) (y) (z) (dimension)
    description: Create Coordinates
    permission-message: You do not have the permission to use this command (Noob?)
